### ISSUE TITLE
Edge: TextArea resizable prop not working correctly

### ISSUE THREAD

**Issue by Lindsay89** [beautifulinteractions/beautiful-react-ui#23]
The resize handler of the TextArea component kind of disappear on the Edge browser

**Comment by anirudh411** [comment]
Hi @Lindsay89 ,
Text area resizable feature is not supported by Edge Browser (non-chromium version).
[Resize Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)

**Comment by antonioru** [comment]
> Hi @Lindsay89 ,
> Text area resizable feature is not supported by Edge Browser (non-chromium version).
> [Resize Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/CSS/resize)

Thank you very much @anirudh411 that's so kind of you to reply
We'll close the issue
